CREATE SEQUENCE s_attach_id INCREMENT BY 5 START WITH 1;
CREATE SEQUENCE s_track_id INCREMENT BY 5 START WITH 1;
CREATE SEQUENCE s_history INCREMENT BY 5 START WITH 1;

CREATE SEQUENCE s_track_num INCREMENT BY 1 START WITH 1;