CREATE TABLE XXITG_SHIPPING_TRACKING (
    ID_TRACKING NUMBER NOT NULL,
    NUM_TRACKING VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    VALIDADOR VARCHAR(100) NOT NULL,
    FECHA_ENTREGA TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(80),
    CREATE_DATE NUMBER,
    CREATE_BY VARCHAR(50),
    LAST_UPDATE_DATE NUMBER,
    LAST_UPDATE_BY VARCHAR(50),
    CONSTRAINT PK_SHIPPING_TRACKING PRIMARY KEY(ID_TRACKING)
);
alter table XXITG_SHIPPING_TRACKING modify FECHA_ENTREGA TIMESTAMP;
CREATE TABLE XXITG_SHIPPING_ATTACHMENTS (
    ID_ATTACHMENT NUMBER NOT NULL,
    FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_EXT VARCHAR(10) NOT NULL,
    FILE_HASH VARCHAR(50),
    DESCRIPTION VARCHAR2(100),
    CONTENT BLOB,
    ID_TRACKING NUMBER NOT NULL,
    CREATE_DATE NUMBER,
    CREATE_BY VARCHAR(50),
    LAST_UPDATE_DATE NUMBER,
    LAST_UPDATE_BY VARCHAR(50),
    CONSTRAINT PK_SHIPPING_ATTACHMENT PRIMARY KEY(ID_ATTACHMENT)
);


CREATE TABLE XXITG_SHIPPING_HISTORY(
    ID_HISTORY NUMBER NOT NULL,
    ID_TRACKING NUMBER,
    ID_ATTACHMENT NUMBER,
    NEW_VALUE VARCHAR(100),
    OLD_VALUE VARCHAR(100),
    CREATE_DATE TIMESTAMP NOT NULL,
    FIELD VARCHAR(50),
    CREATE_BY VARCHAR(50),
    CONSTRAINT PK_SHIPPING_HISTORY2 PRIMARY KEY(ID_HISTORY)
);
--form-data
--primaryFile